### ISSUE TITLE
crop/zoom image-mapped imgs

### ISSUE THREAD

**Issue by slamorsi** [GoMoment/gomoment.github.io#10]
![image](https://cloud.githubusercontent.com/assets/744345/16507627/15f26662-3ee0-11e6-9f84-66ee413e1890.png)
http://ivydocs.gomoment.com/Ivy-Docs2/site/Messages/

**Comment by Alex-Anschuetz** [comment]
cropped - http://ivydocs.gomoment.com/site/Messages/
