### ISSUE TITLE
make intercom help icon a dropdown

### ISSUE THREAD

**Issue by Alex-Anschuetz** [GoMoment/gomoment.github.io#17]
- make the current icon for intercom (help icon) a dropdown that has:

1. Knowledge Base (docs)
2. Live Support (intercom)

**Comment by slamorsi** [comment]
this doesn't belong here?

**Comment by Alex-Anschuetz** [comment]
https://github.com/GoMoment/rev1/pull/1152#issuecomment-236321235

**Comment by slamorsi** [comment]
why re-open here? think there's still some confusion

**Comment by slamorsi** [comment]
it only needs to be a dropdown in rev1. it's fine where it is in docs right now

**Comment by Alex-Anschuetz** [comment]
@slamorsi haha i didnt mean to re-open, think maybe something i did automatically triggered that. Pretty sure we're on the same page, everything should be good. dropdown in rev1, left regular on docs
