### ISSUE TITLE
shouldn't make reference to ivy for choice for general purposes

### ISSUE THREAD

**Issue by slamorsi** [GoMoment/gomoment.github.io#2]
![image](https://cloud.githubusercontent.com/assets/744345/16507332/fb107854-3edd-11e6-9d24-9975dec80a47.png)

**Comment by slamorsi** [comment]
should probably just call it self onboarding rather than anything specific to Choice

**Comment by Alex-Anschuetz** [comment]
I updated, will run by customer success

**Comment by Alex-Anschuetz** [comment]
![screen shot 2016-07-13 at 4 54 48 pm](https://cloud.githubusercontent.com/assets/17972409/16823653/8bb51a54-491a-11e6-909c-940e2eaa65fb.png)

**Comment by slamorsi** [comment]
@Alex-Anschuetz raj and I just reviewed - 

would it be possible to have a an "entry to docs" that has this set up:

"Pick your PMS":
- Opera
- Choice Advantage
- Roomkey 
- Agilysys LMS
- Other

Then based on what they choose, it shows certain things like only for choice would we show 
![image](https://cloud.githubusercontent.com/assets/744345/17266411/b9a54aa8-55ac-11e6-8979-76cb8012da2a.png)

or if this is not possible, we have a general "PMS Docs" Then use that same list to link to specific ones, rather than making Choice a high level info

**Comment by slamorsi** [comment]
also we can take off 
![image](https://cloud.githubusercontent.com/assets/744345/17266452/4c9852a6-55ad-11e6-9820-1149d30342d3.png)

**Comment by Alex-Anschuetz** [comment]
note to self should be all resolved but read thru and double check
