### ISSUE TITLE
unclear instructions for image mapping

### ISSUE THREAD

**Issue by slamorsi** [GoMoment/gomoment.github.io#5]
didn't get what you meant with the labels from the dropdown menu. Could help to make the screenshot bigger/focus on the dropdown area (so just crop out the other stuff)

![image](https://cloud.githubusercontent.com/assets/744345/16507498/ebe97e60-3ede-11e6-9111-9451ea0f81bc.png)

**Comment by slamorsi** [comment]
this one is good
![image](https://cloud.githubusercontent.com/assets/744345/16507509/ff85eae4-3ede-11e6-933f-8be2967a5e70.png)

and then you can use the same image in the other sections. right now after you click the first image with image-mapping it takes you to an image you can't click on. it should stay consistent

**Comment by Alex-Anschuetz** [comment]
working now and consistent http://ivydocs.gomoment.com/site/Managers/
