### ISSUE TITLE
replace test text

### ISSUE THREAD

**Issue by slamorsi** [GoMoment/gomoment.github.io#6]
http://ivydocs.gomoment.com/Ivy-Docs2/site/Managers/#manage-users-page

`2) The first section to complete is the BASIC INFO section. Complete the form with information corresponding to your hotel. If you choose yes for Would you like to allow guests to opt-in by sending Ivy a text message first? , guests can text in to the hotel and will appear on the unverified visits tab (add link when you create brief section explaining visits tabs). Click the 'SAVE & NEXT' button to continue.`

**Comment by Alex-Anschuetz** [comment]
done
