### ISSUE TITLE
new user instructions

### ISSUE THREAD

**Issue by slamorsi** [GoMoment/gomoment.github.io#9]
if we're telling people to manually register then it needs to be explained we'll have to associate them with a hotel 

http://ivydocs.gomoment.com/Ivy-Docs2/site/User-Accounts/

**Comment by Alex-Anschuetz** [comment]
i had tried to address with the first line

![screen shot 2016-07-13 at 1 08 03 pm](https://cloud.githubusercontent.com/assets/17972409/16818119/fa8ed71e-48fa-11e6-960b-3990c1da67d8.png)
